# Generated by Django 6.1.1 on 2026-09-14 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('unidade', models.CharField(choices=[('Kg', 'Kg'), ('Litro', 'Litro'), ('Unidade', 'Unidade')], max_length=20)),
                ('meta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estoque_atual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('venceu', models.BooleanField(default=False)),
                ('acabou_antes', models.BooleanField(default=False)),
            ],
        ),
    ]
